In [70]:
import pandas as pd
import string
import openpyxl
import datetime
import random
import os

In [71]:

# Assuming 'User_database.xlsx' is in the same directory as the notebook/script
excel_file1 = '/kaggle/input/d/mugdhazadkar/user-database/User_database.xlsx'
df_user = pd.read_excel(excel_file1)

# Create key dataframe
headers = ['key_label', 'key_value', 'user_id', 'session_id', 'key_length', 'key_domain', 'generation_datetime']
df_keys = pd.DataFrame(columns=headers)

In [72]:
#user_authentication function

def authenticate_user(username, password):
    user_match = df_user[(df_user['username'] == username) & (df_user['password'] == password)]
    
    if not user_match.empty:
        return 'User authenticated'
    else:
        return 'User not recognized'

# Get user input
username = input("Enter your username: ")
password = input("Enter your password: ")

# Authenticate the user
result = authenticate_user(username, password)
print(result)

Enter your username:
Enter your password:

User not recognized

In [83]:
# replacement for Gokul's function
def random_string(length):
    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for _ in range(length))

# Function to convert bytes to hexadecimal
def bytes_to_hex(data):
    return ''.join(['{:02x}'.format(byte) for byte in data])

#key generation function
def key_generation(user_id, session_id, key_length, key_domain):
    generation_datetime = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    key_value = random_string(key_length)
    key_label = random.randint(10000, 99999)  # Generate a key label
    key_value_hex = bytes_to_hex(key_value.encode('utf-8'))
    
    #create a dictionary with the required data
    new_key =  pd.DataFrame({'key_label':[key_label], 'key_value':[key_value_hex], 'user_id':[user_id], 'session_id':[session_id], 'key_length':[key_length], 'key_domain':[key_domain], 'generation_datetime':[generation_datetime]})
   
    # Use df.append to add the new data entry to the DataFrame
    global df_keys
    df_keys = pd.concat([df_keys, new_key], ignore_index=True)
    print(f"Key generated with key label {key_label}")
    return df_keys

In [96]:
# Function to delete a key from the key database
def key_termination(key_label):
     global df_keys
     try:
        key_label_exists = key_label in df_keys['key_label'].values
        if key_label_exists:
        # Find the row with the specified key_label
            df_keys = df_keys.drop(df_keys[df_keys['key_label'] == key_label].index)
            return df_keys
        else:    
            print(f"Key label '{key_label}' not found in the database.")
            return df_keys
     except Exception as e:
        print(f"An error occurred: {str(e)}")

In [89]:
# Example usage of the key_generation function
user_id = "mugdha"
session_id = 101
key_length = 16
key_domain = "QURE-derived"

key_generation(user_id, session_id, key_length, key_domain)

Key generated with key label 86876

,key_label,key_value,user_id,session_id,key_length,key_domain,generation_datetime
0,79420,364971725036474e386371616b346369,mugdha,101,16,QURE-derived,2023-09-22 10:41:31
1,21279,72336655383872336869303076665061,mugdha,101,16,QURE-derived,2023-09-22 10:41:32
2,13189,795a54463230586139346f74636a7647,mugdha,101,16,QURE-derived,2023-09-22 10:41:33
3,77925,36634c5854706874367562616a316c4c,mugdha,101,16,QURE-derived,2023-09-22 10:41:34
4,44181,51764b35354f4631546b4e39644f7057,mugdha,101,16,QURE-derived,2023-09-22 10:41:35
5,86876,747a6570323250506a58527857503573,mugdha,101,16,QURE-derived,2023-09-22 10:41:39

In [98]:
delete_key = 86876
key_termination(delete_key)

,key_label,key_value,user_id,session_id,key_length,key_domain,generation_datetime
0,79420,364971725036474e386371616b346369,mugdha,101,16,QURE-derived,2023-09-22 10:41:31
1,21279,72336655383872336869303076665061,mugdha,101,16,QURE-derived,2023-09-22 10:41:32
2,13189,795a54463230586139346f74636a7647,mugdha,101,16,QURE-derived,2023-09-22 10:41:33
3,77925,36634c5854706874367562616a316c4c,mugdha,101,16,QURE-derived,2023-09-22 10:41:34
4,44181,51764b35354f4631546b4e39644f7057,mugdha,101,16,QURE-derived,2023-09-22 10:41:35